export const ANCHOREL_CLOSE = "ANCHOREL_CLOSE";
export const ANCHOREL_MENU = "ANCHOREL_MENU";
export const ANCHOREL_CLOSE_LANG = "ANCHOREL_CLOSE_LANG";
export const ANCHOREL_MENU_LANG = "ANCHOREL_MENU_LANG";
export const LANG_EN = "LANG_EN";
export const LANG_VI = "LANG_VI";
export const THEME_DARK_ON = "THEME_DARK_ON";
export const THEME_DARK_OFF = "THEME_DARK_OFF";
export const DRAWER_OPEN = "DRAWER_OPEN";
export const DRAWER_CLOSE = "DRAWER_CLOSE";
export const CREATE_USER_DETAIL = "CREATE_USER_DETAIL";
export const DELETE_USER_DETAIL = "DELETE_USER_DETAIL";
export const DELETE_USER_LIST = "DELETE_USER_LIST";
export const UPDATE_USER_LIST = "UPDATE_USER_LIST";
export const ADD_A_NEW_USER_LIST = "ADD_A_NEW_USER_LIST";
export const SELECT_USER_LIST_DELETE = "SELECT_USER_LIST_DELETE";
export const UPDATE_USER_TRASH = "UPDATE_USER_TRASH";

export const SHOW_ADD_USER_MODAL = "SHOW_ADD_USER_MODAL";
export const CLOSE_ADD_USER_MODAL = "CLOSE_ADD_USER_MODAL";
export const UPDATE_FIRST_NAME_ADD_USER_MODAL = "UPDATE_FIRST_NAME_ADD_USER_MODAL";
export const UPDATE_ERROR_FIRST_NAME_ADD_USER_MODAL = "UPDATE_ERROR_FIRST_NAME_ADD_USER_MODAL";
export const UPDATE_LAST_NAME_ADD_USER_MODAL = "UPDATE_LAST_NAME_ADD_USER_MODAL";
export const UPDATE_ERROR_LAST_NAME_ADD_USER_MODAL = "UPDATE_ERROR_LAST_NAME_ADD_USER_MODAL";
export const UPDATE_EMAIL_ADD_USER_MODAL = "UPDATE_EMAIL_ADD_USER_MODAL";
export const UPDATE_ERROR_EMAIL_ADD_USER_MODAL = "UPDATE_ERROR_EMAIL_ADD_USER_MODAL";

export const UPDATE_ROLE_ADD_USER_MODAL = "UPDATE_ROLE_ADD_USER_MODAL";
export const UPDATE_ERROR_ROLE_ADD_USER_MODAL = "UPDATE_ERROR_ROLE_ADD_USER_MODAL";

export const UPDATE_PASSWORD_ADD_USER_MODAL = "UPDATE_PASSWORD_ADD_USER_MODAL";
export const UPDATE_ERROR_PASSWORD_ADD_USER_MODAL = "UPDATE_ERROR_PASSWORD_ADD_USER_MODAL";

export const SHOW_LOADING_ADD_USER_MODAL = "SHOW_LOADING_ADD_USER_MODAL";
export const CLOSE_LOADING_ADD_USER_MODAL = "CLOSE_LOADING_ADD_USER_MODAL";
export const SHOW_PASSWORD_ADD_USER_MODAL = "SHOW_PASSWORD_ADD_USER_MODAL";
export const HIDE_PASSWORD_ADD_USER_MODAL = "HIDE_PASSWORD_ADD_USER_MODAL";

export const CHECK_REMEMBER_LOGIN = "CHECK_REMEMBER_LOGIN";
export const UNCHECK_REMEMBER_LOGIN = "UNCHECK_REMEMBER_LOGIN";

export const UPDATE_PASSWORD_LOGIN = "UPDATE_PASSWORD_LOGIN";
export const UPDATE_ERROR_PASSWORD_LOGIN = "UPDATE_ERROR_PASSWORD_LOGIN";
export const SHOW_PASSWORD_LOGIN = "SHOW_PASSWORD_LOGIN";
export const HIDE_PASSWORD_LOGIN = "HIDE_PASSWORD_LOGIN";

export const UPDATE_EMAIL_LOGIN = "UPDATE_EMAIL_LOGIN";
export const UPDATE_ERROR_EMAIL_LOGIN = "UPDATE_ERROR_EMAIL_LOGIN";

export const SHOW_DIALOG_MESSAGE = "SHOW_DIALOG_MESSAGE";
export const HIDE_DIALOG_MESSAGE = "HIDE_DIALOG_MESSAGE";
export const UPDATE_MESSAGE_DIALOG = "UPDATE_MESSAGE_DIALOG";

export const UPDATE_USER_AUTH = "UPDATE_USER_AUTH";
export const CLEAR_USER_AUTH = "CLEAR_USER_AUTH";

export const SHOW_LOADING_USER_LIST = "SHOW_LOADING_USER_LIST";
export const CLOSE_LOADING_USER_LIST = "CLOSE_LOADING_USER_LIST";

export const SHOW_LOADING_USER_TRASH_LIST = "SHOW_LOADING_USER_TRASH_LIST";
export const CLOSE_LOADING_USER_TRASH_LIST = "CLOSE_LOADING_USER_TRASH_LIST";
export const SELECT_USER_LIST_RESTORE = "SELECT_USER_LIST_RESTORE";

export const SHOW_DIALOG_CONFIRM_HEADER = "SHOW_DIALOG_CONFIRM_HEADER";
export const HIDE_DIALOG_CONFIRM_HEADER = "HIDE_DIALOG_CONFIRM_HEADER";

export const SHOW_DIALOG_CONFIRM_DELETE_USER_LIST = "SHOW_DIALOG_CONFIRM_DELETE_USER_LIST";
export const HIDE_DIALOG_CONFIRM_DELETE_USER_LIST = "HIDE_DIALOG_CONFIRM_DELETE_USER_LIST";

export const SHOW_DIALOG_DELETE_TRASH = "SHOW_DIALOG_DELETE_TRASH";
export const HIDE_DIALOG_DELETE_TRASH = "HIDE_DIALOG_DELETE_TRASH";

export const UPDATE_LIST_MOVIE = "UPDATE_LIST_MOVIE";
export const SHOW_DIALOG_LOADING_LIST_MOVIE = "SHOW_DIALOG_LOADING_LIST_MOVIE";
export const HIDE_DIALOG_LOADING_LIST_MOVIE = "HIDE_DIALOG_LOADING_LIST_MOVIE";
export const UPDATE_LIST_GENRES = "UPDATE_LIST_GENRES";

export const SHOW_DIALOG_LOADING = "SHOW_DIALOG_LOADING";
export const HIDE_DIALOG_LOADING = "HIDE_DIALOG_LOADING";
